### ISSUE TITLE
Highsmith example page appears to be broken

### ISSUE THREAD

**Issue by davidnhale** [openseadragon/example-images#3]
Going to http://openseadragon.github.io/example-images/highsmith/index.html, it appears that the path to load the DZI is broken.

**Comment by iangilman** [comment]
Interesting... I didn't even realize that file was there. It should probably be removed... it's certainly not supported. If you want to see highsmith in action, just go to the front page of http://openseadragon.github.io/

**Comment by davidnhale** [comment]
Actually, I appreciate having a simple example demonstrating how to use openseadragon, rather than what it says on the home page to "You can examine the source of this page to see how to include OpenSeadragon in a page. " In fact, it would be nice to have html pages for each of the example-images folders, to make it easier to contrast the code for each example.

**Comment by iangilman** [comment]
We do have example code for the specific image types on the website, for example:

http://openseadragon.github.io/examples/tilesource-dzi/
http://openseadragon.github.io/examples/tilesource-osm/

I agree "examine the source" is a lame intro on the front page though... we should put some real source inline there.

I would like to focus on improving the website, since that's what's publicly available... anything in this repository is a bit buried. Also, making sure the openseadragon.js in this repository stays up to date would add complexity to our release system.

Note that the openseadragon/openseadragon repository also has `test/demo/basic.html`, which is a good way to play around with a running OpenSeadragon.

I think the todo item here is to improve the "installing" section on the website.

**Comment by iangilman** [comment]
I've added a mention of basic.html in the readme: https://github.com/openseadragon/openseadragon/commit/1a5f712aee055fae756bb7f9d3b686a210650d09

**Comment by iangilman** [comment]
I've now improved the "installing" section:

http://openseadragon.github.io/#installing

... and removed the outdated file from this repo.

Thanks for drawing my attention to this!
